# 分段写，data是一个list有两个dict
URL: https://www.baidu.com
log:
    file_name: test.log
    back_up: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'